[package]
name = "robotiq_85_msgs"
version = "1.0.1"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.3"
serde = { version = "1", optional = true, features = ["derive"] }
builtin_interfaces = "*"
std_msgs = "*"

[features]
serde = ['dep:serde', 'rosidl_runtime_rs/serde', 'builtin_interfaces/serde', 'std_msgs/serde']
